<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Setting;

class ComprehensiveSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // إعدادات الموقع العامة
            [
                'key' => 'site_name',
                'value' => 'إنجب',
                'type' => 'string',
                'group' => 'general',
                'label' => 'اسم الموقع',
                'description' => 'اسم الموقع الذي يظهر في الهيدر والفوتر',
                'is_public' => true,
            ],
            [
                'key' => 'site_description',
                'value' => 'منصة التسوق الإلكتروني الرائدة في الكويت',
                'type' => 'text',
                'group' => 'general',
                'label' => 'وصف الموقع',
                'description' => 'وصف مختصر للموقع يظهر في محركات البحث',
                'is_public' => true,
            ],
            [
                'key' => 'site_logo',
                'value' => 'logos/site-logo.png',
                'type' => 'file',
                'group' => 'general',
                'label' => 'شعار الموقع الرئيسي',
                'description' => 'الشعار الذي يظهر في الهيدر',
                'is_public' => true,
            ],
            [
                'key' => 'site_footer_logo',
                'value' => 'logos/site-footer-logo.png',
                'type' => 'file',
                'group' => 'design',
                'label' => 'شعار الفوتر',
                'description' => 'الشعار الذي يظهر في الفوتر (يمكن أن يكون مختلف عن شعار الهيدر)',
                'is_public' => true,
            ],
            [
                'key' => 'site_favicon',
                'value' => 'favicon.ico',
                'type' => 'file',
                'group' => 'general',
                'label' => 'أيقونة الموقع',
                'description' => 'الأيقونة التي تظهر في تبويب المتصفح',
                'is_public' => true,
            ],
            [
                'key' => 'contact_phone',
                'value' => '+965 50 123 4567',
                'type' => 'string',
                'group' => 'general',
                'label' => 'رقم الهاتف',
                'description' => 'رقم الهاتف الرئيسي للتواصل',
                'is_public' => true,
            ],
            [
                'key' => 'contact_email',
                'value' => 'info@engeb.com',
                'type' => 'string',
                'group' => 'general',
                'label' => 'البريد الإلكتروني',
                'description' => 'البريد الإلكتروني الرئيسي للتواصل',
                'is_public' => true,
            ],
            [
                'key' => 'contact_address',
                'value' => 'مدينة الكويت، دولة الكويت',
                'type' => 'text',
                'group' => 'general',
                'label' => 'العنوان',
                'description' => 'العنوان الرئيسي للشركة',
                'is_public' => true,
            ],
            [
                'key' => 'default_language',
                'value' => 'ar',
                'type' => 'string',
                'group' => 'general',
                'label' => 'اللغة الافتراضية',
                'description' => 'اللغة الافتراضية للموقع',
                'is_public' => true,
            ],
            [
                'key' => 'timezone',
                'value' => 'Asia/Kuwait',
                'type' => 'string',
                'group' => 'general',
                'label' => 'المنطقة الزمنية',
                'description' => 'المنطقة الزمنية للموقع',
                'is_public' => true,
            ],
            [
                'key' => 'currency',
                'value' => 'KWD',
                'type' => 'string',
                'group' => 'general',
                'label' => 'العملة',
                'description' => 'العملة الافتراضية للموقع',
                'is_public' => true,
            ],
            [
                'key' => 'currency_symbol',
                'value' => 'د.ك',
                'type' => 'string',
                'group' => 'general',
                'label' => 'رمز العملة',
                'description' => 'رمز العملة الذي يظهر مع الأسعار',
                'is_public' => true,
            ],

            // إعدادات البريد الإلكتروني
            [
                'key' => 'mail_driver',
                'value' => 'smtp',
                'type' => 'string',
                'group' => 'email',
                'label' => 'نوع بروتوكول البريد',
                'description' => 'نوع بروتوكول إرسال البريد الإلكتروني',
                'is_public' => false,
            ],
            [
                'key' => 'mail_host',
                'value' => 'smtp.gmail.com',
                'type' => 'string',
                'group' => 'email',
                'label' => 'خادم البريد الإلكتروني',
                'description' => 'عنوان خادم البريد الإلكتروني',
                'is_public' => false,
            ],
            [
                'key' => 'mail_port',
                'value' => '587',
                'type' => 'number',
                'group' => 'email',
                'label' => 'منفذ البريد الإلكتروني',
                'description' => 'رقم المنفذ المستخدم لإرسال البريد',
                'is_public' => false,
            ],
            [
                'key' => 'mail_username',
                'value' => 'noreply@engeb.com',
                'type' => 'string',
                'group' => 'email',
                'label' => 'اسم المستخدم للبريد',
                'description' => 'اسم المستخدم لحساب البريد الإلكتروني',
                'is_public' => false,
            ],
            [
                'key' => 'mail_password',
                'value' => '',
                'type' => 'string',
                'group' => 'email',
                'label' => 'كلمة مرور البريد',
                'description' => 'كلمة مرور حساب البريد الإلكتروني',
                'is_public' => false,
            ],
            [
                'key' => 'mail_encryption',
                'value' => 'tls',
                'type' => 'string',
                'group' => 'email',
                'label' => 'نوع التشفير',
                'description' => 'نوع التشفير المستخدم في البريد الإلكتروني',
                'is_public' => false,
            ],
            [
                'key' => 'mail_from_address',
                'value' => 'noreply@engeb.com',
                'type' => 'string',
                'group' => 'email',
                'label' => 'عنوان المرسل الافتراضي',
                'description' => 'العنوان الذي يظهر كمرسل للرسائل',
                'is_public' => false,
            ],
            [
                'key' => 'mail_from_name',
                'value' => 'إنجب',
                'type' => 'string',
                'group' => 'email',
                'label' => 'اسم المرسل الافتراضي',
                'description' => 'الاسم الذي يظهر كمرسل للرسائل',
                'is_public' => false,
            ],

            // إعدادات الدفع
            [
                'key' => 'payment_methods',
                'value' => '["cash", "card", "knet", "wallet"]',
                'type' => 'json',
                'group' => 'payment',
                'label' => 'طرق الدفع المتاحة',
                'description' => 'قائمة بطرق الدفع المتاحة في الموقع',
                'is_public' => true,
            ],
            [
                'key' => 'knet_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'payment',
                'label' => 'تفعيل KNET',
                'description' => 'تفعيل أو إلغاء تفعيل دفع KNET',
                'is_public' => false,
            ],
            [
                'key' => 'knet_merchant_id',
                'value' => '',
                'type' => 'string',
                'group' => 'payment',
                'label' => 'معرف التاجر KNET',
                'description' => 'معرف التاجر الخاص بـ KNET',
                'is_public' => false,
            ],
            [
                'key' => 'stripe_enabled',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'payment',
                'label' => 'تفعيل Stripe',
                'description' => 'تفعيل أو إلغاء تفعيل دفع Stripe',
                'is_public' => false,
            ],
            [
                'key' => 'stripe_public_key',
                'value' => '',
                'type' => 'string',
                'group' => 'payment',
                'label' => 'مفتاح Stripe العام',
                'description' => 'المفتاح العام لـ Stripe',
                'is_public' => false,
            ],
            [
                'key' => 'stripe_secret_key',
                'value' => '',
                'type' => 'string',
                'group' => 'payment',
                'label' => 'مفتاح Stripe السري',
                'description' => 'المفتاح السري لـ Stripe',
                'is_public' => false,
            ],
            [
                'key' => 'delivery_fee',
                'value' => '2.000',
                'type' => 'number',
                'group' => 'payment',
                'label' => 'رسوم التوصيل',
                'description' => 'رسوم التوصيل الافتراضية بالدينار الكويتي',
                'is_public' => true,
            ],
            [
                'key' => 'free_delivery_threshold',
                'value' => '25.000',
                'type' => 'number',
                'group' => 'payment',
                'label' => 'حد التوصيل المجاني',
                'description' => 'الحد الأدنى للطلب للحصول على توصيل مجاني',
                'is_public' => true,
            ],

            // إعدادات السيو
            [
                'key' => 'meta_title',
                'value' => 'إنجب - منصة التسوق الإلكتروني الرائدة في الكويت',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'عنوان الموقع (Meta Title)',
                'description' => 'العنوان الذي يظهر في محركات البحث',
                'is_public' => true,
            ],
            [
                'key' => 'meta_description',
                'value' => 'اكتشف أفضل المنتجات الغذائية والاستهلاكية من موردين موثوقين في الكويت. تسوق بسهولة وأمان مع إنجب.',
                'type' => 'text',
                'group' => 'seo',
                'label' => 'وصف الموقع (Meta Description)',
                'description' => 'الوصف الذي يظهر في محركات البحث',
                'is_public' => true,
            ],
            [
                'key' => 'meta_keywords',
                'value' => 'تسوق إلكتروني, كويت, منتجات غذائية, بقالة, توصيل, إنجب',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'كلمات مفتاحية',
                'description' => 'الكلمات المفتاحية للموقع مفصولة بفواصل',
                'is_public' => true,
            ],
            [
                'key' => 'og_title',
                'value' => 'إنجب - منصة التسوق الإلكتروني',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'عنوان Open Graph',
                'description' => 'العنوان الذي يظهر عند مشاركة الموقع في وسائل التواصل',
                'is_public' => true,
            ],
            [
                'key' => 'og_description',
                'value' => 'منصة التسوق الإلكتروني الرائدة في الكويت',
                'type' => 'text',
                'group' => 'seo',
                'label' => 'وصف Open Graph',
                'description' => 'الوصف الذي يظهر عند مشاركة الموقع في وسائل التواصل',
                'is_public' => true,
            ],
            [
                'key' => 'og_image',
                'value' => 'images/og-image.jpg',
                'type' => 'file',
                'group' => 'seo',
                'label' => 'صورة Open Graph',
                'description' => 'الصورة التي تظهر عند مشاركة الموقع في وسائل التواصل',
                'is_public' => true,
            ],
            [
                'key' => 'google_analytics_id',
                'value' => '',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'معرف Google Analytics',
                'description' => 'معرف Google Analytics لتتبع زوار الموقع',
                'is_public' => false,
            ],
            [
                'key' => 'google_tag_manager_id',
                'value' => '',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'معرف Google Tag Manager',
                'description' => 'معرف Google Tag Manager لإدارة التتبع',
                'is_public' => false,
            ],
            [
                'key' => 'facebook_pixel_id',
                'value' => '',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'معرف Facebook Pixel',
                'description' => 'معرف Facebook Pixel لتتبع التحويلات',
                'is_public' => false,
            ],

            // إعدادات التصميم
            [
                'key' => 'primary_color',
                'value' => '#3B82F6',
                'type' => 'string',
                'group' => 'design',
                'label' => 'اللون الأساسي',
                'description' => 'اللون الأساسي للموقع',
                'is_public' => true,
            ],
            [
                'key' => 'secondary_color',
                'value' => '#10B981',
                'type' => 'string',
                'group' => 'design',
                'label' => 'اللون الثانوي',
                'description' => 'اللون الثانوي للموقع',
                'is_public' => true,
            ],
            [
                'key' => 'accent_color',
                'value' => '#F59E0B',
                'type' => 'string',
                'group' => 'design',
                'label' => 'لون التمييز',
                'description' => 'لون التمييز للعناصر المهمة',
                'is_public' => true,
            ],
            [
                'key' => 'custom_css',
                'value' => '/* أكواد CSS مخصصة */\n/* يمكنك إضافة أي أكواد CSS هنا */',
                'type' => 'text',
                'group' => 'design',
                'label' => 'أكواد CSS مخصصة',
                'description' => 'أكواد CSS مخصصة يتم تطبيقها على الموقع',
                'is_public' => true,
            ],
            [
                'key' => 'admin_custom_css',
                'value' => '/* أكواد CSS مخصصة للوحة الإدارة */\n/* يمكنك إضافة أي أكواد CSS هنا */',
                'type' => 'text',
                'group' => 'design',
                'label' => 'أكواد CSS مخصصة للإدارة',
                'description' => 'أكواد CSS مخصصة يتم تطبيقها على لوحة الإدارة',
                'is_public' => false,
            ],
            [
                'key' => 'theme_mode',
                'value' => 'light',
                'type' => 'string',
                'group' => 'design',
                'label' => 'وضع الثيم',
                'description' => 'وضع الثيم الافتراضي للموقع',
                'is_public' => true,
            ],
            [
                'key' => 'font_family',
                'value' => 'Cairo, sans-serif',
                'type' => 'string',
                'group' => 'design',
                'label' => 'عائلة الخط',
                'description' => 'عائلة الخط المستخدمة في الموقع',
                'is_public' => true,
            ],

            // إعدادات وسائل التواصل الاجتماعي
            [
                'key' => 'facebook_url',
                'value' => 'https://facebook.com/engeb',
                'type' => 'string',
                'group' => 'general',
                'label' => 'رابط Facebook',
                'description' => 'رابط صفحة Facebook الرسمية',
                'is_public' => true,
            ],
            [
                'key' => 'twitter_url',
                'value' => 'https://twitter.com/engeb',
                'type' => 'string',
                'group' => 'general',
                'label' => 'رابط Twitter',
                'description' => 'رابط حساب Twitter الرسمي',
                'is_public' => true,
            ],
            [
                'key' => 'instagram_url',
                'value' => 'https://instagram.com/engeb',
                'type' => 'string',
                'group' => 'general',
                'label' => 'رابط Instagram',
                'description' => 'رابط حساب Instagram الرسمي',
                'is_public' => true,
            ],
            [
                'key' => 'linkedin_url',
                'value' => 'https://linkedin.com/company/engeb',
                'type' => 'string',
                'group' => 'general',
                'label' => 'رابط LinkedIn',
                'description' => 'رابط صفحة LinkedIn الرسمية',
                'is_public' => true,
            ],
            [
                'key' => 'youtube_url',
                'value' => 'https://youtube.com/engeb',
                'type' => 'string',
                'group' => 'general',
                'label' => 'رابط YouTube',
                'description' => 'رابط قناة YouTube الرسمية',
                'is_public' => true,
            ],
            [
                'key' => 'whatsapp_number',
                'value' => '+965501234567',
                'type' => 'string',
                'group' => 'general',
                'label' => 'رقم WhatsApp',
                'description' => 'رقم WhatsApp للتواصل',
                'is_public' => true,
            ],

            // وضع المطور
            [
                'key' => 'maintenance_mode',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'developer',
                'label' => 'وضع الصيانة',
                'description' => 'تفعيل وضع الصيانة لإيقاف الموقع مؤقتاً',
                'is_public' => false,
            ],
            [
                'key' => 'maintenance_message',
                'value' => 'نحن نعمل على تحسين الموقع، سنعود قريباً!',
                'type' => 'text',
                'group' => 'developer',
                'label' => 'رسالة الصيانة',
                'description' => 'الرسالة التي تظهر للمستخدمين في وضع الصيانة',
                'is_public' => false,
            ],
            [
                'key' => 'debug_mode',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'developer',
                'label' => 'وضع التصحيح',
                'description' => 'تفعيل وضع التصحيح لعرض الأخطاء',
                'is_public' => false,
            ],
            [
                'key' => 'api_rate_limit',
                'value' => '100',
                'type' => 'number',
                'group' => 'developer',
                'label' => 'حد معدل API',
                'description' => 'عدد الطلبات المسموح بها في الدقيقة للـ API',
                'is_public' => false,
            ],
            [
                'key' => 'cache_duration',
                'value' => '3600',
                'type' => 'number',
                'group' => 'developer',
                'label' => 'مدة التخزين المؤقت',
                'description' => 'مدة التخزين المؤقت بالثواني',
                'is_public' => false,
            ],
            [
                'key' => 'log_level',
                'value' => 'error',
                'type' => 'string',
                'group' => 'developer',
                'label' => 'مستوى السجلات',
                'description' => 'مستوى تسجيل الأحداث (debug, info, warning, error)',
                'is_public' => false,
            ],
        ];

        foreach ($settings as $settingData) {
            Setting::updateOrCreate(
                ['key' => $settingData['key']],
                $settingData
            );
        }

        $this->command->info('تم إنشاء جميع الإعدادات بنجاح!');
    }
}

