<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vendor;
use App\Models\Governorate;
use App\Models\City;

class FeaturedVendorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get Kuwait governorate and cities
        $kuwait = Governorate::where('name', 'الكويت')->first();
        $kuwaitCity = City::where('name', 'الكويت')->first();

        $featuredVendors = [
            [
                'name' => 'Fresh Market Kuwait',
                'name_ar' => 'سوق الكويت الطازج',
                'email' => 'info@freshmarketkw.com',
                'phone' => '+96512345678',
                'password' => bcrypt('password123'),
                'commercial_record' => 'CR123456789',
                'address' => 'شارع الخليج العربي، الكويت',
                'governorate_id' => $kuwait?->id,
                'city_id' => $kuwaitCity?->id,
                'business_categories' => ['fruits-vegetables', 'dairy', 'meat-poultry'],
                'business_description' => 'متجر متخصص في المنتجات الطازجة والعضوية',
                'description' => 'نقدم أفضل المنتجات الطازجة والعضوية من المزارع المحلية',
                'logo' => null,
                'rating' => 4.8,
                'reviews_count' => 150,
                'orders_count' => 2500,
                'total_sales' => 125000.000,
                'status' => 'approved',
                'is_active' => true,
                'is_featured' => true,
                'is_fresh' => true,
                'category' => 'خضروات وفواكه',
                'delivery_fee' => 2.000,
                'free_delivery_threshold' => 25.000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Golden Dairy Co.',
                'name_ar' => 'شركة الألبان الذهبية',
                'email' => 'info@goldendairy.com',
                'phone' => '+96523456789',
                'password' => bcrypt('password123'),
                'commercial_record' => 'CR234567890',
                'address' => 'منطقة الشويخ الصناعية، الكويت',
                'governorate_id' => $kuwait?->id,
                'city_id' => $kuwaitCity?->id,
                'business_categories' => ['dairy', 'frozen'],
                'business_description' => 'شركة رائدة في منتجات الألبان والجبن',
                'description' => 'أفضل منتجات الألبان الطازجة والجبن المحلي',
                'logo' => null,
                'rating' => 4.6,
                'reviews_count' => 200,
                'orders_count' => 3200,
                'total_sales' => 180000.000,
                'status' => 'approved',
                'is_active' => true,
                'is_featured' => true,
                'is_fresh' => true,
                'category' => 'منتجات الألبان',
                'delivery_fee' => 1.500,
                'free_delivery_threshold' => 30.000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Premium Meat House',
                'name_ar' => 'بيت اللحوم المميز',
                'email' => 'info@premiummeat.com',
                'phone' => '+96534567890',
                'password' => bcrypt('password123'),
                'commercial_record' => 'CR345678901',
                'address' => 'سوق المباركية، الكويت',
                'governorate_id' => $kuwait?->id,
                'city_id' => $kuwaitCity?->id,
                'business_categories' => ['meat-poultry', 'frozen'],
                'business_description' => 'متجر متخصص في اللحوم الحلال والدواجن',
                'description' => 'أفضل اللحوم الحلال والدواجن الطازجة',
                'logo' => null,
                'rating' => 4.7,
                'reviews_count' => 120,
                'orders_count' => 1800,
                'total_sales' => 95000.000,
                'status' => 'approved',
                'is_active' => true,
                'is_featured' => true,
                'is_fresh' => true,
                'category' => 'لحوم ودواجن',
                'delivery_fee' => 3.000,
                'free_delivery_threshold' => 40.000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bakery Delights',
                'name_ar' => 'مخبز الأفراح',
                'email' => 'info@bakerydelights.com',
                'phone' => '+96545678901',
                'password' => bcrypt('password123'),
                'commercial_record' => 'CR456789012',
                'address' => 'شارع سالم المبارك، الكويت',
                'governorate_id' => $kuwait?->id,
                'city_id' => $kuwaitCity?->id,
                'business_categories' => ['bakery', 'snacks'],
                'business_description' => 'مخبز متخصص في الخبز العربي والأوروبي',
                'description' => 'أشهى أنواع الخبز والحلويات الطازجة',
                'logo' => null,
                'rating' => 4.5,
                'reviews_count' => 80,
                'orders_count' => 1200,
                'total_sales' => 65000.000,
                'status' => 'approved',
                'is_active' => true,
                'is_featured' => true,
                'is_fresh' => true,
                'category' => 'مخبوزات',
                'delivery_fee' => 2.500,
                'free_delivery_threshold' => 20.000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Clean & Fresh',
                'name_ar' => 'نظيف وطازج',
                'email' => 'info@cleanfresh.com',
                'phone' => '+96556789012',
                'password' => bcrypt('password123'),
                'commercial_record' => 'CR567890123',
                'address' => 'منطقة الجهراء، الكويت',
                'governorate_id' => $kuwait?->id,
                'city_id' => $kuwaitCity?->id,
                'business_categories' => ['cleaning', 'personal-care'],
                'business_description' => 'متجر متخصص في منتجات التنظيف والعناية الشخصية',
                'description' => 'أفضل منتجات التنظيف والعناية الشخصية',
                'logo' => null,
                'rating' => 4.4,
                'reviews_count' => 90,
                'orders_count' => 1500,
                'total_sales' => 75000.000,
                'status' => 'approved',
                'is_active' => true,
                'is_featured' => true,
                'is_fresh' => false,
                'category' => 'منظفات',
                'delivery_fee' => 1.000,
                'free_delivery_threshold' => 15.000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baby Care Center',
                'name_ar' => 'مركز رعاية الأطفال',
                'email' => 'info@babycare.com',
                'phone' => '+96567890123',
                'password' => bcrypt('password123'),
                'commercial_record' => 'CR678901234',
                'address' => 'شارع فهد السالم، الكويت',
                'governorate_id' => $kuwait?->id,
                'city_id' => $kuwaitCity?->id,
                'business_categories' => ['baby-care', 'personal-care'],
                'business_description' => 'متجر متخصص في منتجات الأطفال والعناية بهم',
                'description' => 'أفضل منتجات الأطفال والعناية بهم',
                'logo' => null,
                'rating' => 4.9,
                'reviews_count' => 300,
                'orders_count' => 2800,
                'total_sales' => 140000.000,
                'status' => 'approved',
                'is_active' => true,
                'is_featured' => true,
                'is_fresh' => false,
                'category' => 'منتجات الأطفال',
                'delivery_fee' => 2.000,
                'free_delivery_threshold' => 35.000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Beverage World',
                'name_ar' => 'عالم المشروبات',
                'email' => 'info@beverageworld.com',
                'phone' => '+96578901234',
                'password' => bcrypt('password123'),
                'commercial_record' => 'CR789012345',
                'address' => 'منطقة الشويخ، الكويت',
                'governorate_id' => $kuwait?->id,
                'city_id' => $kuwaitCity?->id,
                'business_categories' => ['beverages', 'snacks'],
                'business_description' => 'متجر متخصص في المشروبات والعصائر',
                'description' => 'أفضل المشروبات والعصائر الطبيعية',
                'logo' => null,
                'rating' => 4.3,
                'reviews_count' => 60,
                'orders_count' => 900,
                'total_sales' => 45000.000,
                'status' => 'approved',
                'is_active' => true,
                'is_featured' => true,
                'is_fresh' => false,
                'category' => 'مشروبات',
                'delivery_fee' => 1.500,
                'free_delivery_threshold' => 25.000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Snack Paradise',
                'name_ar' => 'جنة الوجبات الخفيفة',
                'email' => 'info@snackparadise.com',
                'phone' => '+96589012345',
                'password' => bcrypt('password123'),
                'commercial_record' => 'CR890123456',
                'address' => 'شارع أحمد الجابر، الكويت',
                'governorate_id' => $kuwait?->id,
                'city_id' => $kuwaitCity?->id,
                'business_categories' => ['snacks', 'beverages'],
                'business_description' => 'متجر متخصص في الوجبات الخفيفة والحلويات',
                'description' => 'أشهى الوجبات الخفيفة والحلويات',
                'logo' => null,
                'rating' => 4.2,
                'reviews_count' => 70,
                'orders_count' => 1100,
                'total_sales' => 55000.000,
                'status' => 'approved',
                'is_active' => true,
                'is_featured' => true,
                'is_fresh' => false,
                'category' => 'وجبات خفيفة',
                'delivery_fee' => 1.000,
                'free_delivery_threshold' => 20.000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($featuredVendors as $vendorData) {
            Vendor::create($vendorData);
        }
    }
}
